version: TroEngine-{branch} 0.1.{build}
branches:
  only:
  - master
  - development
skip_tags: true
image: Visual Studio 2017
configuration:
- Debug
- Release
environment:
  platform: x86
build:
  project: TroEngine.sln
  verbosity: minimal
before_package:
- ps: >-
    Copy-Item C:\projects\TroEngine\$env:CONFIGURATION\TroEngine.exe C:\projects\TroEngine\TroEngine\EngineResources\.

    Copy-Item C:\projects\TroEngine\README.md C:\projects\TroEngine\TroEngine\EngineResources\.
artifacts:
- path: TroEngine\EngineResources
  name: TroEngine
deploy:
- provider: GitHub
  auth_token:
    secure: GeYx4HYpDpN6dKUH00nJz0Yzbe9g98uB74ulCIMOCcsPighlNM5m/E5mGnCuLo+r
  artifact: TroEngine
  force_update: true
  on:
    branch: master
    CONFIGURATION: Release